import React from 'react';
import '../styles/AdminDashboard.css';

const mockReports = [
  { id: 'RPT1001', reportType: 'Monthly Revenue', status: 'Completed', date: '2025-04-01', generatedBy: 'Admin' },
  { id: 'RPT1002', reportType: 'Active Bookings', status: 'In Progress', date: '2025-04-05', generatedBy: 'Admin' },
  { id: 'RPT1003', reportType: 'Customer Feedback', status: 'Completed', date: '2025-04-07', generatedBy: 'Admin' },
  { id: 'RPT1004', reportType: 'Provider Performance', status: 'Completed', date: '2025-04-10', generatedBy: 'Admin' },
];

const Reports = () => {
  return (
    <div className="section-wrapper">
      <header className="dashboard-header">
        <h1>Reports</h1>
        <p>View generated reports or request new ones</p>
      </header>

      <div className="table-container">
        <table className="admin-table">
          <thead>
            <tr>
              <th>Report ID</th>
              <th>Report Type</th>
              <th>Status</th>
              <th>Date</th>
              <th>Generated By</th>
            </tr>
          </thead>
          <tbody>
            {mockReports.map(report => (
              <tr key={report.id}>
                <td>{report.id}</td>
                <td>{report.reportType}</td>
                <td>{report.status}</td>
                <td>{report.date}</td>
                <td>{report.generatedBy}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Reports;
